
USE `NOV`;

CREATE TABLE IF NOT EXISTS `OPERATION_DATA` (
	`ID` INT(15) NOT NULL AUTO_INCREMENT,
	`SUBSCRIBER_ID` VARCHAR(9) NOT NULL UNIQUE,
	`MSISDN` VARCHAR(11) NOT NULL UNIQUE,
	`START_TIME` DATETIME NOT NULL,
	`END_TIME` DATETIME NOT NULL,
	`COST` VARCHAR(10) NOT NULL,
	PRIMARY KEY (`ID`)
);
