
INSERT INTO OPERATION_DATA(ID, OPERATION_STATUS, XML_REQ, XML_RESP, OPERATION_NAME, TARIFF, OPERATOR_NAME, NUMER_TYPE, GIT ) VALUES (1, 'SUCCESS', 'xmlReq', 'xmlResp', 'topup', 'taktak','era', 'standard', 'git');
INSERT INTO OPERATION_DATA(ID, OPERATION_STATUS, XML_REQ, XML_RESP, OPERATION_NAME, TARIFF, OPERATOR_NAME, NUMER_TYPE, GIT ) VALUES (2, 'SUCCESS', 'xmlReq', 'xmlResp', 'topup2', 'taktak2','era2', 'standard2', 'git2');
