
INSERT INTO OPERATION_DATA(ID,STATUS_OPERATION, XML_REQ, XML_RESP, NAME_OPERATION, TARIFF, OPERATOR, NUMER_TYPE, GIT ) VALUES (1, 'SUCCESS', 'xmlReq', 'xmlResp', 'topup', 'taktak','era', 'standard', 'git');
INSERT INTO OPERATION_DATA(ID,STATUS_OPERATION, XML_REQ, XML_RESP, NAME_OPERATION, TARIFF, OPERATOR, NUMER_TYPE, GIT ) VALUES (2, 'SUCCESS', 'xmlReq', 'xmlResp', 'topup2', 'taktak2','era', 'standard', 'git');
