DROP TABLE IF EXISTS OPERATION_DATA;


CREATE TABLE IF NOT EXISTS OPERATION_DATA (
	ID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
	SUBSCRIBER_ID VARCHAR(9) NOT NULL UNIQUE,
	MSISDN VARCHAR(11) NOT NULL UNIQUE,
	START_TIME DATETIME NOT NULL,
	END_TIME DATETIME NOT NULL,
	COST VARCHAR(10) NOT NULL,
	PRIMARY KEY (`ID`)
);

ALTER TABLE OPERATION_DATA
ADD COLUMN  STATUS_OPERATION VARCHAR(10) NOT NULL,
ADD COLUMN  XML_WEJ BLOB,
ADD COLUMN  XML_WYJ BLOB,
ADD COLUMN	NAME_OPERATION VARCHAR(10) NOT NULL,
ADD COLUMN	TARIFF VARCHAR(10) NOT NULL,
ADD COLUMN	OPERATOR VARCHAR(10) NOT NULL,
ADD COLUMN	NUMER_TYPE VARCHAR(10) NOT NULL,
ADD COLUMN	GIT VARCHAR(10) NOT NULL;