DROP TABLE IF EXISTS OPERATION_DATA;


CREATE TABLE IF NOT EXISTS OPERATION_DATA (
	ID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
	STATUS_OPERATION VARCHAR(10) NOT NULL,
	XML_REQ CLOB,
	XML_RESP CLOB,
	NAME_OPERATION VARCHAR(10) NOT NULL,
	TARIFF VARCHAR(10) NOT NULL,
	OPERATOR VARCHAR(10) NOT NULL,
	NUMER_TYPE VARCHAR(10) NOT NULL,
	GIT VARCHAR(10) NOT NULL,
	PRIMARY KEY (`ID`)
);